name: CI

on:
  push:
    paths:
      - 'lab3-prosta-gra/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Set executable permission for gradlew
        working-directory: lab3-prosta-gra
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: lab3-prosta-gra
        run: ./gradlew build
